name: Update BLAS

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight UTC
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull latest changes
      run: git pull origin main

    - name: Update BLAS
      run: |
        git submodule update --recursive --remote
        git add src && git commit -m "Update BLAS"
        git push origin main