name: Update BLAS

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight UTC
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure Git
      run: |
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Create and Checkout a New Branch
      run: |
        git checkout -b update_submodule
      continue-on-error: true

    - name: Update BLAS
      run: |
        git submodule update --recursive --remote
        git status
        git add src && git commit -m "Update BLAS"
        git push origin update_submodule

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update_submodule
        title: "Update BLAS"
        body: "Automated update of BLAS"
        base: main
